{% set name = "EDFlib-Python" %}
{% set version = "1.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/EDFlib-Python-{{ version }}.tar.gz
  sha256: 42de3b7980809f37fcc44e3cddc837a3237b69b937a81335dd1f9ffaaf3f2e19

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.17
    - python >={{ python_min }}

test:
  imports:
    - EDFlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.teuniz.net/edflib_python/
  summary: Library to read/write EDF+/BDF+ files written in pure Python by the same author as the original EDFlib.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sappelhoff
