{% set name = "EDFlib-Python" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EDFlib-Python-{{ version }}.tar.gz
  sha256: dbd1d2cf80013f8627b0b08bb969e157b70de5eb241156052e7dea15fd4c06bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy >=1.17
    - python >=3.5

test:
  imports:
    - EDFlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.teuniz.net/edflib_python/
  summary: Library to read/write EDF+/BDF+ files written in pure Python by the same author as the original EDFlib.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sappelhoff
