{% set name = "EDFlib-Python" %}
{% set version = "1.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EDFlib-Python-{{ version }}.tar.gz
  sha256: 81f671a69876d0ea8b62da3139615c39512d108e5097981c5e1b6e30b691acb8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy >=1.17
    - python >=3.5

test:
  imports:
    - EDFlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.teuniz.net/edflib_python/
  summary: Library to read/write EDF+/BDF+ files written in pure Python by the same author as the original EDFlib.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sappelhoff
